language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6
  
script: pytest